# Setup
title: Sherwin's Blog
url: https://chensherwinnie.github.io
paginate: 1
baseurl: "/blog"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Sherwin Chen
  email: sherwinnie@wiseyestudio.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Archive
    url: /archive

  - title: About
    url: /about

defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
